perf/131: task finished
project-studying-dotnet/Streetcode-Admin-March-02 pull request #169
Opened 2024-03-31 16:30 UTC by ShpurykGleb

2024-03-31 18:52 UTC, cyberfoxie approved these changes

2024-04-01 05:36 UTC, YaroslavDZ approved these changes

2024-04-01 05:41 UTC, YaroslavDZ reviewed
Streetcode.BLL\Util\DateToStringConverter.cs(42,5): error SA1508: A closing brace should not be preceded by a blank line.
![зображення_2024-04-01_084052157](https://github.com/project-studying-dotnet/Streetcode-Admin-March-02/assets/51023046/18ce7b93-79db-41d1-8faa-36d362728287)

2024-04-01 05:44 UTC, YaroslavDZ requested changes
Streetcode.BLL\Util\DateToStringConverter.cs(42,5): error SA1508: A closing brace should not be preceded by a blank line.

2024-04-01 06:10 UTC, closed without merging